from __future__ import annotations

DEFAULT_TELEGRAM_UI_LANGUAGE = "en"

_EN: dict[str, str] = {
    "draft_checkpoint_saved_db": "Draft checkpoint saved in database.",
    "only_editors_add_words": "Only editors can add words.",
    "only_editors_edit_words": "Only editors can edit published words.",
    "only_editors_edit_images": "Only editors can edit published word images.",
    "no_permission_add_words": "You do not have permission to add words.",
    "selected_word_unavailable": "Selected word is no longer available.",
    "add_words_flow_inactive": "This draft is no longer active.",
    "add_words_flow_cancelled": "Add-words flow cancelled.",
    "word_edit_task_inactive": "This word edit task is no longer active.",
    "image_review_task_inactive": "This image review task is no longer active.",
    "image_review_flow_inactive": "This image review flow is no longer active.",
    "image_review_completed": "Image review completed.",
    "image_selected": "Image selected.",
    "image_skipped": "Image skipped.",
    "start_image_generation": "Starting image generation...",
    "image_generation_unavailable": "Local AI image generation is currently unavailable.",
    "auto_images_unavailable": "Auto image generation is currently unavailable right now.",
    "send_photo_not_text": "Send a photo, not text, for this image review step.",
    "updating_image_prompt": "Updating image prompt... 0/1",
    "searching_pixabay": "Searching Pixabay... 0/1",
    "saving_uploaded_photo": "Saving uploaded photo... 0/1",
    "parsing_draft": "Parsing draft... 0/1",
    "parsing_draft_failed_timeout": "Parsing draft... failed\nOllama timed out while parsing this text. Try a shorter text, a faster model, or increase OLLAMA_TIMEOUT_SEC.",
    "parsing_draft_failed_generic": "Parsing draft... failed\nCould not parse this text. Please try again or simplify the input.",
    "re_recognizing_draft": "Re-recognizing draft... 0/1",
    "smart_parsing_unavailable": "Smart parsing is currently unavailable right now.",
    "saving_approved_draft": "Saving approved draft... 0/1",
    "publishing_content_pack": "Publishing content pack... 0/1",
    "draft_finalization_failed": "Draft finalization failed.",
    "published_content_not_found": "Published content pack not found.",
    "no_vocabulary_items_found": "No vocabulary items found in this content pack.",
    "words_menu_prompt": "Words menu.",
    "choose_topic_start_training": "Choose a topic to start training.",
    "choose_topic_start_training_help": "Choose a topic to start training.\nUse /help to see commands.",
    "quick_actions_title": "Quick actions:",
    "help_title": "Available commands:\n{commands}",
    "version_title": "Bot version",
    "version_line": "Version: {version}",
    "build_line": "Build: {build_number}",
    "git_sha_line": "Git SHA: {git_sha}",
    "git_branch_line": "Branch: {branch}",
    "send_raw_lesson_text": "Send the raw lesson text in one message. The format can be messy.\nUse /cancel to stop.",
    "send_raw_lesson_text_with_menu": "Send the raw lesson text in one message. The format can be messy. Use /cancel to stop.",
    "active_add_words_flow_exists": "You already have an active add-words flow. Send the text now or use /cancel.",
    "choose_topic_edit_words": "Choose a topic to edit words.",
    "choose_topic_edit_images": "Choose a topic to edit word images.",
    "choose_word_to_edit": "Choose a word to edit.",
    "session_started": "Session started.",
    "continue_current_session": "Continuing your current session.",
    "previous_session_discarded": "Previous session discarded.",
    "no_active_session_send_start": "There is no active session anymore. Send /start.",
    "no_active_session_begin": "No active session. Send /start to begin.",
    "choose_mode": "Choose a training mode.",
    "choose_lesson": "Choose all words in the topic or a specific lesson.",
    "active_session_exists": "You already have an active session.\nTopic: {topic_id}\nLesson: {lesson_id}\nMode: {mode}\nProgress: {current_position}/{total_items}\nDo you want to continue or start over?",
    "correct": "Correct.",
    "not_quite": "Not quite. Correct answer: {expected_answer}.",
    "session_complete": "\nSession complete: {correct_answers}/{total_questions} correct.",
    "training_topics": "Training Topics",
    "add_words": "Add Words",
    "edit_words": "Edit Words",
    "edit_word_image": "Edit Word Image",
    "approve_auto_images": "Approve + Auto Images",
    "manual_image_review": "Manual Image Review",
    "publish_without_images": "Publish Without Images",
    "show_json": "Show JSON",
    "re_recognize_draft": "Re-recognize Draft",
    "edit_text": "Edit Text",
    "cancel": "Cancel",
    "approve_disabled": "Approve Disabled",
    "review_disabled": "Review Disabled",
    "publish_disabled": "Publish Disabled",
    "continue": "Continue",
    "start_over": "Start Over",
    "all_topic_words": "All Topic Words",
    "easy": "Easy",
    "medium": "Medium",
    "hard": "Hard",
    "game_mode": "🎮 Game Mode",
    "choose_game_mode": "Pick a game difficulty.",
    "game_session_started": "🎮 Game on! 🔥 Streak: {streak_days} days",
    "game_round_started": "🎮 Next round! 🔥 Streak: {streak_days} days",
    "game_correct": "🎉 Correct!",
    "game_almost": "😢 Almost!",
    "game_feedback": "{feedback}\nProgress: {progress}/{total}\n⭐ Stars: {stars}",
    "game_session_complete": "🎉 Level complete!\nSession stars: ⭐ {session_stars}\nChest: +{chest_stars}⭐\nEarned: +{total_earned}⭐\nTotal stars: ⭐ {total_stars}\n🔥 Streak: {streak_days} days",
    "next_round": "➡️ Next round",
    "repeat": "🔁 Repeat",
    "menu": "🏠 Menu",
    "no_topics": "No topics",
    "no_items": "No items",
    "no_words": "No words",
    "words_menu_title": "Words menu.",
    "quick_actions_title": "Quick actions:",
    "published_choose_word_image": "Choose a word to edit its image.",
    "search_images": "Search Images",
    "generate_image": "Generate Image",
    "edit_search_query": "Edit Search Query",
    "edit_prompt": "Edit Prompt",
    "attach_photo": "Attach Photo",
    "skip_for_now": "Skip for now",
    "next_6": "Next 6",
    "previous_6": "Previous 6",
    "use_n": "Use {index}",
    "choose_another_word_to_edit": "Choose another word to edit.",
    "edit_cancelled_choose_word": "Edit cancelled. Choose a word to edit.",
    "send_updated_word_format": "Send the updated word as one line.\nFormat: English: Translation",
    "send_one_line_word_format": "Send one line in the format: English: Translation",
    "current_value": "Current value:\n{value}",
    "word_updated": "Word updated.\n{word} — {translation}\nChanges are now available in training.",
    "current_image_intro": "Current image.\nYou can keep it, search Pixabay, generate a local image, edit the prompt, or attach your own photo.",
    "no_current_image_intro": "No current image is saved for this word yet.\nYou can search Pixabay, generate a local image, edit the prompt, or attach your own photo.",
    "pixabay_search_progress": "Searching Pixabay {current}/{total}...",
    "pixabay_candidates_ready": "Pixabay candidates ready {current}/{total}.",
    "loading_next_pixabay": "Loading next Pixabay candidates {current}/{total}...",
    "loading_previous_pixabay": "Loading previous Pixabay candidates {current}/{total}...",
    "send_new_full_prompt": "Send a new full image prompt for this word as one message.",
    "current_prompt": "Current prompt:\n{prompt}",
    "send_new_search_query": "Send a new Pixabay search query for this word as one message.",
    "current_query": "Current query:\n{query}",
    "attach_one_photo": "Attach one photo for this word.",
    "uploaded_photo_attached": "Uploaded photo attached.",
    "draft_updated_from_text": "Draft updated from edited text.",
    "edit_word_list_instruction": "Edit only the word list below, then send the full edited version back as one message.\nUse one line per item in the format: English: Translation",
    "approved_draft_saved_generating_prompts": "Approved draft saved.\n{checkpoint}\nGenerating image prompts... 0/1",
    "image_prompts_generated_starting_review": "Image prompts generated.\n{checkpoint}\nImage prompts: {prompt_count}\nStarting image review...",
    "image_prompts_generated_publishing": "Image prompts generated.\n{checkpoint}\nImage prompts: {prompt_count}\nPublishing content pack... 0/1",
    "image_prompts_generated_saved_continue_review": "Image prompts generated and saved.\n{checkpoint}\nImage prompts: {prompt_count}\nEverything is saved. Continue image review in the messages below.",
    "draft_approved_published": "Draft approved and published.\n{destination}\nAdded words: {item_count}\nNew words are now available in the bot.",
    "content_pack_published_generating_images": "Content pack published.\n{destination}\nAdded words: {item_count}\nGenerating images... {processed}/{total}",
    "draft_approved_images_generated": "Draft approved and images generated.\n{destination}\nGenerated images: {generated_count}\nYou can edit the image for a specific word if needed.",
    "choose_word_edit_image": "Choose a word to edit its image.",
    "no_changes_choose_another_word": "No changes made. Choose another word to edit.",
    "image_review_completed_published": "Image review completed and content pack published.\n{destination}\nNew words are now available in the bot.",
    "send_not_text_for_photo": "Send a photo, not text, for this image review step.",
    "updating_image_prompt_failed": "Updating image prompt... failed\nCould not update this prompt. Please try again.",
    "prompt_updated": "Prompt updated.",
    "searching_pixabay_failed": "Searching Pixabay... failed\nCould not search with this query. Please try again.",
    "pixabay_candidates_updated": "Pixabay candidates updated.",
    "local_candidates_generating": "Generating local image candidates {current}/{total}...",
    "local_candidates_ready": "Local image candidates ready {current}/{total}",
    "pixabay_search_query": "Pixabay search query: {query}",
    "image_review_no_candidates_loaded": "No candidates loaded yet.",
    "pixabay_candidates_page": "Pixabay candidates page {page}",
    "image_review_local_ai_candidates": "Local AI candidates.",
    "image_review_progress": "Reviewing images {current}/{total}",
    "image_review_prompt_line": "Prompt: {prompt}",
    "image_review_prompt_usage_note": "Prompt is used for local AI generation.",
}

_RU: dict[str, str] = {
    "draft_checkpoint_saved_db": "Черновик сохранён в базе данных.",
    "only_editors_add_words": "Только редакторы могут добавлять слова.",
    "only_editors_edit_words": "Только редакторы могут редактировать опубликованные слова.",
    "only_editors_edit_images": "Только редакторы могут редактировать изображения слов.",
    "no_permission_add_words": "У вас нет прав для добавления слов.",
    "selected_word_unavailable": "Выбранное слово больше недоступно.",
    "add_words_flow_inactive": "Этот черновик больше не активен.",
    "add_words_flow_cancelled": "Добавление слов отменено.",
    "word_edit_task_inactive": "Эта задача редактирования слова больше не активна.",
    "image_review_task_inactive": "Эта задача проверки изображений больше не активна.",
    "image_review_flow_inactive": "Этот поток проверки изображений больше не активен.",
    "image_review_completed": "Проверка изображений завершена.",
    "image_selected": "Изображение выбрано.",
    "image_skipped": "Изображение пропущено.",
    "start_image_generation": "Запускаю генерацию изображения...",
    "image_generation_unavailable": "Локальная AI-генерация изображений сейчас недоступна.",
    "auto_images_unavailable": "Автоматическая генерация изображений сейчас недоступна.",
    "send_photo_not_text": "Для этого шага отправьте фото, а не текст.",
    "updating_image_prompt": "Обновляю промпт изображения... 0/1",
    "searching_pixabay": "Ищу в Pixabay... 0/1",
    "saving_uploaded_photo": "Сохраняю загруженное фото... 0/1",
    "parsing_draft": "Разбираю черновик... 0/1",
    "parsing_draft_failed_timeout": "Разбор черновика... ошибка\nOllama не ответила вовремя. Попробуйте более короткий текст, более быструю модель или увеличьте OLLAMA_TIMEOUT_SEC.",
    "parsing_draft_failed_generic": "Разбор черновика... ошибка\nНе удалось разобрать этот текст. Попробуйте ещё раз или упростите ввод.",
    "re_recognizing_draft": "Повторно распознаю черновик... 0/1",
    "smart_parsing_unavailable": "Smart parsing сейчас недоступен.",
    "saving_approved_draft": "Сохраняю подтверждённый черновик... 0/1",
    "publishing_content_pack": "Публикую пакет контента... 0/1",
    "draft_finalization_failed": "Не удалось финализировать черновик.",
    "published_content_not_found": "Опубликованный пакет контента не найден.",
    "no_vocabulary_items_found": "В этом пакете нет слов.",
    "words_menu_prompt": "Меню слов.",
    "choose_topic_start_training": "Выберите тему для тренировки.",
    "choose_topic_start_training_help": "Выберите тему для тренировки.\nИспользуйте /help для списка команд.",
    "quick_actions_title": "Быстрые действия:",
    "help_title": "Доступные команды:\n{commands}",
    "version_title": "Версия бота",
    "version_line": "Версия: {version}",
    "build_line": "Сборка: {build_number}",
    "git_sha_line": "Git SHA: {git_sha}",
    "git_branch_line": "Ветка: {branch}",
    "send_raw_lesson_text": "Отправьте сырой текст урока одним сообщением. Формат может быть неаккуратным.\nИспользуйте /cancel для отмены.",
    "send_raw_lesson_text_with_menu": "Отправьте сырой текст урока одним сообщением. Формат может быть неаккуратным. Используйте /cancel для отмены.",
    "active_add_words_flow_exists": "У вас уже есть активный поток добавления слов. Отправьте текст сейчас или используйте /cancel.",
    "choose_topic_edit_words": "Выберите тему для редактирования слов.",
    "choose_topic_edit_images": "Выберите тему для редактирования изображений слов.",
    "choose_word_to_edit": "Выберите слово для редактирования.",
    "session_started": "Сессия началась.",
    "continue_current_session": "Продолжаю текущую сессию.",
    "previous_session_discarded": "Предыдущая сессия сброшена.",
    "no_active_session_send_start": "Активной сессии больше нет. Отправьте /start.",
    "no_active_session_begin": "Нет активной сессии. Отправьте /start, чтобы начать.",
    "choose_mode": "Выберите режим тренировки.",
    "choose_lesson": "Выберите все слова темы или конкретный урок.",
    "active_session_exists": "У вас уже есть активная сессия.\nТема: {topic_id}\nУрок: {lesson_id}\nРежим: {mode}\nПрогресс: {current_position}/{total_items}\nПродолжить или начать заново?",
    "correct": "Верно.",
    "not_quite": "Не совсем так. Правильный ответ: {expected_answer}.",
    "session_complete": "\nСессия завершена: {correct_answers}/{total_questions} правильных ответов.",
    "training_topics": "Темы тренировки",
    "add_words": "Добавить слова",
    "edit_words": "Редактировать слова",
    "edit_word_image": "Редактировать картинку слова",
    "approve_auto_images": "Подтвердить + авто-картинки",
    "manual_image_review": "Ручная проверка картинок",
    "publish_without_images": "Опубликовать без картинок",
    "show_json": "Показать JSON",
    "re_recognize_draft": "Распознать заново",
    "edit_text": "Редактировать текст",
    "cancel": "Отмена",
    "approve_disabled": "Подтверждение недоступно",
    "review_disabled": "Проверка недоступна",
    "publish_disabled": "Публикация недоступна",
    "continue": "Продолжить",
    "start_over": "Начать заново",
    "all_topic_words": "Все слова темы",
    "easy": "Легко",
    "medium": "Средне",
    "hard": "Сложно",
    "game_mode": "🎮 Режим игры",
    "choose_game_mode": "Выберите сложность игры.",
    "game_session_started": "🎮 Игра началась! 🔥 Серия: {streak_days} дн.",
    "game_round_started": "🎮 Новый раунд! 🔥 Серия: {streak_days} дн.",
    "game_correct": "🎉 Верно!",
    "game_almost": "😢 Почти!",
    "game_feedback": "{feedback}\nПрогресс: {progress}/{total}\n⭐ Звёзды: {stars}",
    "game_session_complete": "🎉 Уровень пройден!\nЗвёзды за сессию: ⭐ {session_stars}\nСундук: +{chest_stars}⭐\nПолучено: +{total_earned}⭐\nВсего звёзд: ⭐ {total_stars}\n🔥 Серия: {streak_days} дн.",
    "next_round": "➡️ Следующий раунд",
    "repeat": "🔁 Повторить",
    "menu": "🏠 Меню",
    "no_topics": "Нет тем",
    "no_items": "Нет элементов",
    "no_words": "Нет слов",
    "words_menu_title": "Меню слов.",
    "quick_actions_title": "Быстрые действия:",
    "published_choose_word_image": "Выберите слово, чтобы изменить его изображение.",
    "search_images": "Искать картинки",
    "generate_image": "Сгенерировать картинку",
    "edit_search_query": "Изменить поисковый запрос",
    "edit_prompt": "Изменить промпт",
    "attach_photo": "Прикрепить фото",
    "skip_for_now": "Пропустить пока",
    "next_6": "Следующие 6",
    "previous_6": "Предыдущие 6",
    "use_n": "Выбрать {index}",
    "choose_another_word_to_edit": "Выберите другое слово для редактирования.",
    "edit_cancelled_choose_word": "Редактирование отменено. Выберите слово для редактирования.",
    "send_updated_word_format": "Отправьте обновлённое слово одной строкой.\nФормат: English: Translation",
    "send_one_line_word_format": "Отправьте одну строку в формате: English: Translation",
    "current_value": "Текущее значение:\n{value}",
    "word_updated": "Слово обновлено.\n{word} — {translation}\nИзменения уже доступны в тренировке.",
    "current_image_intro": "Текущее изображение.\nМожно оставить его, поискать в Pixabay, сгенерировать локально, изменить промпт или прикрепить своё фото.",
    "no_current_image_intro": "Для этого слова пока нет сохранённого изображения.\nМожно поискать в Pixabay, сгенерировать локально, изменить промпт или прикрепить своё фото.",
    "pixabay_search_progress": "Ищу в Pixabay {current}/{total}...",
    "pixabay_candidates_ready": "Кандидаты Pixabay готовы {current}/{total}.",
    "loading_next_pixabay": "Загружаю следующие кандидаты Pixabay {current}/{total}...",
    "loading_previous_pixabay": "Загружаю предыдущие кандидаты Pixabay {current}/{total}...",
    "send_new_full_prompt": "Отправьте новый полный промпт для этого слова одним сообщением.",
    "current_prompt": "Текущий промпт:\n{prompt}",
    "send_new_search_query": "Отправьте новый запрос Pixabay для этого слова одним сообщением.",
    "current_query": "Текущий запрос:\n{query}",
    "attach_one_photo": "Прикрепите одно фото для этого слова.",
    "uploaded_photo_attached": "Загруженное фото прикреплено.",
    "draft_updated_from_text": "Черновик обновлён из отредактированного текста.",
    "edit_word_list_instruction": "Отредактируйте только список слов ниже, затем отправьте всю отредактированную версию одним сообщением.\nИспользуйте по одной строке на элемент в формате: English: Translation",
    "approved_draft_saved_generating_prompts": "Подтверждённый черновик сохранён.\n{checkpoint}\nГенерирую промпты для изображений... 0/1",
    "image_prompts_generated_starting_review": "Промпты изображений сгенерированы.\n{checkpoint}\nПромптов: {prompt_count}\nЗапускаю проверку изображений...",
    "image_prompts_generated_publishing": "Промпты изображений сгенерированы.\n{checkpoint}\nПромптов: {prompt_count}\nПубликую пакет контента... 0/1",
    "image_prompts_generated_saved_continue_review": "Промпты изображений сгенерированы и сохранены.\n{checkpoint}\nПромптов: {prompt_count}\nВсё сохранено. Продолжайте проверку изображений в сообщениях ниже.",
    "draft_approved_published": "Черновик подтверждён и опубликован.\n{destination}\nДобавлено слов: {item_count}\nНовые слова уже доступны в боте.",
    "content_pack_published_generating_images": "Пакет контента опубликован.\n{destination}\nДобавлено слов: {item_count}\nГенерирую изображения... {processed}/{total}",
    "draft_approved_images_generated": "Черновик подтверждён, изображения сгенерированы.\n{destination}\nСгенерировано изображений: {generated_count}\nПри необходимости можно отредактировать картинку конкретного слова.",
    "choose_word_edit_image": "Выберите слово, чтобы изменить его изображение.",
    "no_changes_choose_another_word": "Изменений нет. Выберите другое слово для редактирования.",
    "image_review_completed_published": "Проверка изображений завершена, пакет контента опубликован.\n{destination}\nНовые слова уже доступны в боте.",
    "send_not_text_for_photo": "Для этого шага проверки изображений отправьте фото, а не текст.",
    "updating_image_prompt_failed": "Не удалось обновить промпт изображения.\nПопробуйте ещё раз.",
    "prompt_updated": "Промпт обновлён.",
    "searching_pixabay_failed": "Не удалось выполнить поиск по этому запросу.\nПопробуйте ещё раз.",
    "pixabay_candidates_updated": "Кандидаты Pixabay обновлены.",
    "local_candidates_generating": "Генерирую локальные кандидаты {current}/{total}...",
    "local_candidates_ready": "Локальные кандидаты готовы {current}/{total}",
    "pixabay_search_query": "Поиск в Pixabay: {query}",
    "image_review_no_candidates_loaded": "Кандидаты ещё не загружены.",
    "pixabay_candidates_page": "Кандидаты Pixabay, страница {page}",
    "image_review_local_ai_candidates": "Локальные AI-кандидаты.",
    "image_review_progress": "Проверка изображений {current}/{total}",
    "image_review_prompt_line": "Промпт: {prompt}",
    "image_review_prompt_usage_note": "Этот промпт используется для локальной AI-генерации.",
}

_UK: dict[str, str] = {
    "draft_checkpoint_saved_db": "Чернетку збережено в базі даних.",
    "only_editors_add_words": "Лише редактори можуть додавати слова.",
    "only_editors_edit_words": "Лише редактори можуть редагувати опубліковані слова.",
    "only_editors_edit_images": "Лише редактори можуть редагувати зображення слів.",
    "no_permission_add_words": "У вас немає прав для додавання слів.",
    "selected_word_unavailable": "Вибране слово більше недоступне.",
    "add_words_flow_inactive": "Ця чернетка більше не активна.",
    "add_words_flow_cancelled": "Додавання слів скасовано.",
    "word_edit_task_inactive": "Це завдання редагування слова більше не активне.",
    "image_review_task_inactive": "Це завдання перевірки зображень більше не активне.",
    "image_review_flow_inactive": "Цей потік перевірки зображень більше не активний.",
    "image_review_completed": "Перевірку зображень завершено.",
    "image_selected": "Зображення вибрано.",
    "image_skipped": "Зображення пропущено.",
    "start_image_generation": "Запускаю генерацію зображення...",
    "image_generation_unavailable": "Локальна AI-генерація зображень зараз недоступна.",
    "auto_images_unavailable": "Автоматична генерація зображень зараз недоступна.",
    "send_photo_not_text": "Для цього кроку надішліть фото, а не текст.",
    "updating_image_prompt": "Оновлюю промпт зображення... 0/1",
    "searching_pixabay": "Шукаю в Pixabay... 0/1",
    "saving_uploaded_photo": "Зберігаю завантажене фото... 0/1",
    "parsing_draft": "Розбираю чернетку... 0/1",
    "parsing_draft_failed_timeout": "Розбір чернетки... помилка\nOllama не відповіла вчасно. Спробуйте коротший текст, швидшу модель або збільшіть OLLAMA_TIMEOUT_SEC.",
    "parsing_draft_failed_generic": "Розбір чернетки... помилка\nНе вдалося розібрати цей текст. Спробуйте ще раз або спростіть введення.",
    "re_recognizing_draft": "Повторно розпізнаю чернетку... 0/1",
    "smart_parsing_unavailable": "Smart parsing зараз недоступний.",
    "saving_approved_draft": "Зберігаю підтверджену чернетку... 0/1",
    "publishing_content_pack": "Публікую пакет контенту... 0/1",
    "draft_finalization_failed": "Не вдалося фіналізувати чернетку.",
    "published_content_not_found": "Опублікований пакет контенту не знайдено.",
    "no_vocabulary_items_found": "У цьому пакеті немає слів.",
    "words_menu_prompt": "Меню слів.",
    "choose_topic_start_training": "Виберіть тему для тренування.",
    "choose_topic_start_training_help": "Виберіть тему для тренування.\nВикористовуйте /help для списку команд.",
    "quick_actions_title": "Швидкі дії:",
    "help_title": "Доступні команди:\n{commands}",
    "version_title": "Версія бота",
    "version_line": "Версія: {version}",
    "build_line": "Збірка: {build_number}",
    "git_sha_line": "Git SHA: {git_sha}",
    "git_branch_line": "Гілка: {branch}",
    "send_raw_lesson_text": "Надішліть сирий текст уроку одним повідомленням. Формат може бути неохайним.\nВикористовуйте /cancel для скасування.",
    "send_raw_lesson_text_with_menu": "Надішліть сирий текст уроку одним повідомленням. Формат може бути неохайним. Використовуйте /cancel для скасування.",
    "active_add_words_flow_exists": "У вас уже є активний потік додавання слів. Надішліть текст зараз або використовуйте /cancel.",
    "choose_topic_edit_words": "Виберіть тему для редагування слів.",
    "choose_topic_edit_images": "Виберіть тему для редагування зображень слів.",
    "choose_word_to_edit": "Виберіть слово для редагування.",
    "session_started": "Сесію розпочато.",
    "continue_current_session": "Продовжую поточну сесію.",
    "previous_session_discarded": "Попередню сесію скинуто.",
    "no_active_session_send_start": "Активної сесії більше немає. Надішліть /start.",
    "no_active_session_begin": "Немає активної сесії. Надішліть /start, щоб почати.",
    "choose_mode": "Виберіть режим тренування.",
    "choose_lesson": "Виберіть усі слова теми або конкретний урок.",
    "active_session_exists": "У вас уже є активна сесія.\nТема: {topic_id}\nУрок: {lesson_id}\nРежим: {mode}\nПрогрес: {current_position}/{total_items}\nПродовжити чи почати заново?",
    "correct": "Правильно.",
    "not_quite": "Не зовсім так. Правильна відповідь: {expected_answer}.",
    "session_complete": "\nСесію завершено: {correct_answers}/{total_questions} правильних відповідей.",
    "training_topics": "Теми тренування",
    "add_words": "Додати слова",
    "edit_words": "Редагувати слова",
    "edit_word_image": "Редагувати зображення слова",
    "approve_auto_images": "Підтвердити + авто-зображення",
    "manual_image_review": "Ручна перевірка зображень",
    "publish_without_images": "Опублікувати без зображень",
    "show_json": "Показати JSON",
    "re_recognize_draft": "Розпізнати знову",
    "edit_text": "Редагувати текст",
    "cancel": "Скасувати",
    "approve_disabled": "Підтвердження недоступне",
    "review_disabled": "Перевірка недоступна",
    "publish_disabled": "Публікація недоступна",
    "continue": "Продовжити",
    "start_over": "Почати заново",
    "all_topic_words": "Усі слова теми",
    "easy": "Легко",
    "medium": "Середньо",
    "hard": "Складно",
    "game_mode": "🎮 Режим гри",
    "choose_game_mode": "Оберіть складність гри.",
    "game_session_started": "🎮 Гру розпочато! 🔥 Серія: {streak_days} дн.",
    "game_round_started": "🎮 Новий раунд! 🔥 Серія: {streak_days} дн.",
    "game_correct": "🎉 Правильно!",
    "game_almost": "😢 Майже!",
    "game_feedback": "{feedback}\nПрогрес: {progress}/{total}\n⭐ Зірки: {stars}",
    "game_session_complete": "🎉 Рівень пройдено!\nЗірки за сесію: ⭐ {session_stars}\nСкриня: +{chest_stars}⭐\nОтримано: +{total_earned}⭐\nУсього зірок: ⭐ {total_stars}\n🔥 Серія: {streak_days} дн.",
    "next_round": "➡️ Наступний раунд",
    "repeat": "🔁 Повторити",
    "menu": "🏠 Меню",
    "no_topics": "Немає тем",
    "no_items": "Немає елементів",
    "no_words": "Немає слів",
    "words_menu_title": "Меню слів.",
    "published_choose_word_image": "Виберіть слово, щоб змінити його зображення.",
    "search_images": "Шукати зображення",
    "generate_image": "Згенерувати зображення",
    "edit_search_query": "Змінити пошуковий запит",
    "edit_prompt": "Змінити промпт",
    "attach_photo": "Прикріпити фото",
    "skip_for_now": "Пропустити поки що",
    "next_6": "Наступні 6",
    "previous_6": "Попередні 6",
    "use_n": "Обрати {index}",
    "choose_another_word_to_edit": "Виберіть інше слово для редагування.",
    "edit_cancelled_choose_word": "Редагування скасовано. Виберіть слово для редагування.",
    "send_updated_word_format": "Надішліть оновлене слово одним рядком.\nФормат: English: Translation",
    "send_one_line_word_format": "Надішліть один рядок у форматі: English: Translation",
    "current_value": "Поточне значення:\n{value}",
    "word_updated": "Слово оновлено.\n{word} — {translation}\nЗміни вже доступні у тренуванні.",
    "current_image_intro": "Поточне зображення.\nМожна залишити його, пошукати в Pixabay, згенерувати локально, змінити промпт або прикріпити своє фото.",
    "no_current_image_intro": "Для цього слова поки що немає збереженого зображення.\nМожна пошукати в Pixabay, згенерувати локально, змінити промпт або прикріпити своє фото.",
    "pixabay_search_progress": "Шукаю в Pixabay {current}/{total}...",
    "pixabay_candidates_ready": "Кандидати Pixabay готові {current}/{total}.",
    "loading_next_pixabay": "Завантажую наступних кандидатів Pixabay {current}/{total}...",
    "loading_previous_pixabay": "Завантажую попередніх кандидатів Pixabay {current}/{total}...",
    "send_new_full_prompt": "Надішліть новий повний промпт для цього слова одним повідомленням.",
    "current_prompt": "Поточний промпт:\n{prompt}",
    "send_new_search_query": "Надішліть новий запит Pixabay для цього слова одним повідомленням.",
    "current_query": "Поточний запит:\n{query}",
    "attach_one_photo": "Прикріпіть одне фото для цього слова.",
    "uploaded_photo_attached": "Завантажене фото прикріплено.",
    "draft_updated_from_text": "Чернетку оновлено з відредагованого тексту.",
    "edit_word_list_instruction": "Відредагуйте лише список слів нижче, а потім надішліть усю відредаговану версію одним повідомленням.\nВикористовуйте по одному рядку на елемент у форматі: English: Translation",
    "approved_draft_saved_generating_prompts": "Підтверджену чернетку збережено.\n{checkpoint}\nГенерую промпти для зображень... 0/1",
    "image_prompts_generated_starting_review": "Промпти зображень згенеровано.\n{checkpoint}\nПромптів: {prompt_count}\nЗапускаю перевірку зображень...",
    "image_prompts_generated_publishing": "Промпти зображень згенеровано.\n{checkpoint}\nПромптів: {prompt_count}\nПублікую пакет контенту... 0/1",
    "image_prompts_generated_saved_continue_review": "Промпти зображень згенеровано та збережено.\n{checkpoint}\nПромптів: {prompt_count}\nУсе збережено. Продовжуйте перевірку зображень у повідомленнях нижче.",
    "draft_approved_published": "Чернетку підтверджено та опубліковано.\n{destination}\nДодано слів: {item_count}\nНові слова вже доступні в боті.",
    "content_pack_published_generating_images": "Пакет контенту опубліковано.\n{destination}\nДодано слів: {item_count}\nГенерую зображення... {processed}/{total}",
    "draft_approved_images_generated": "Чернетку підтверджено, зображення згенеровано.\n{destination}\nЗгенеровано зображень: {generated_count}\nЗа потреби можна відредагувати зображення конкретного слова.",
    "choose_word_edit_image": "Виберіть слово, щоб змінити його зображення.",
    "no_changes_choose_another_word": "Змін немає. Виберіть інше слово для редагування.",
    "image_review_completed_published": "Перевірку зображень завершено, пакет контенту опубліковано.\n{destination}\nНові слова вже доступні в боті.",
    "send_not_text_for_photo": "Для цього кроку перевірки зображень надішліть фото, а не текст.",
    "updating_image_prompt_failed": "Не вдалося оновити промпт зображення.\nСпробуйте ще раз.",
    "prompt_updated": "Промпт оновлено.",
    "searching_pixabay_failed": "Не вдалося виконати пошук за цим запитом.\nСпробуйте ще раз.",
    "pixabay_candidates_updated": "Кандидатів Pixabay оновлено.",
    "local_candidates_generating": "Генерую локальних кандидатів {current}/{total}...",
    "local_candidates_ready": "Локальні кандидати готові {current}/{total}",
    "pixabay_search_query": "Пошук у Pixabay: {query}",
    "image_review_no_candidates_loaded": "Кандидатів ще не завантажено.",
    "pixabay_candidates_page": "Кандидати Pixabay, сторінка {page}",
    "image_review_local_ai_candidates": "Локальні AI-кандидати.",
    "image_review_progress": "Перевірка зображень {current}/{total}",
    "image_review_prompt_line": "Промпт: {prompt}",
    "image_review_prompt_usage_note": "Цей промпт використовується для локальної AI-генерації.",
}

_STRINGS = {
    "en": _EN,
    "ru": _RU,
    "uk": _UK,
}


def _validate_catalogs() -> None:
    expected = set(_STRINGS[DEFAULT_TELEGRAM_UI_LANGUAGE])
    for language, bundle in _STRINGS.items():
        keys = set(bundle)
        if keys != expected:
            missing = sorted(expected - keys)
            extra = sorted(keys - expected)
            raise RuntimeError(
                f"Telegram UI catalog mismatch for {language}: missing={missing} extra={extra}"
            )


_validate_catalogs()


def telegram_ui_text(key: str, *, language: str = DEFAULT_TELEGRAM_UI_LANGUAGE, **kwargs: object) -> str:
    bundle = _STRINGS.get(language, _STRINGS[DEFAULT_TELEGRAM_UI_LANGUAGE])
    template = bundle.get(key)
    if template is None:
        template = _STRINGS[DEFAULT_TELEGRAM_UI_LANGUAGE][key]
    return template.format(**kwargs)


def supported_telegram_ui_languages() -> tuple[str, ...]:
    return tuple(sorted(_STRINGS))
